version: '3'

services:
  postgres:
    image: 'postgres:11.5'
    container_name: 'nestjs-query-db'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - '5432'
    ports:
      - ${DB_PORT}:5432

      #  sudo docker-compose up -d
      #  sudo docker-compose down